#!/bin/bash

if [ -t 0 ] && [ -t 1 ]; then
    V=1
fi

[ "$V" ] && source /lib/gentoo/functions.sh

options=(
--changed-deps
--deep
--keep-going
--newuse
--update
--with-bdeps=y
)

cmd=(emerge "${options[@]}" "$@" @world)

[ "$V" ] && ebegin "${cmd[*]}"

"${cmd[@]}"

[ "$V" ] && eend $?
