#!/bin/bash

source /lib/gentoo/functions.sh

options=(
--changed-deps
--deep
--keep-going
--newuse
--update
--with-bdeps=y
)

cmd=(emerge "${options[@]}" "$@" @world)

ebegin "${cmd[*]}"

"${cmd[@]}"

eend $?
