#!/bin/bash

source /lib/gentoo/functions.sh

options='
--changed-deps
--deep
--keep-going
--newuse
--update
--with-bdeps=y
'

cmd=
for i in emerge $options "$@" world; do
    cmd="$cmd '$i'"
done

ebegin $cmd
    eval $cmd
eend $?
